config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get 'questions/index' => 'questions#index', as: :all_questions

  get 'questions/new' => 'questions#new', as: :new_question

  post 'questions/create' => 'questions#create', as: :questions

  get 'questions/:id' => 'questions#show', as: :question

  delete 'questions/:id' => 'questions#destroy'

  get 'questions/:id/edit' => 'questions#edit', as: :edit_question

  patch 'questions/:id' => 'questions#update'

  post 'questions/:question_id/answers/create' => 'answers#create', as: :answer_create

  get 'questions/:question_id/answers/:id/edit' => 'answers#edit', as: :edit_answer

  put 'questions/:question_id/answers/:id' => 'answers#update', as: :update_answer

  delete 'questions/:question_id/answers/:id' => 'answers#destroy', as: :delete_answer

  post 'questions/:question_id/answers/:answer_id/answer_comments/create' => 'answer_comments#create', as: :answer_comment_create

  get 'questions/:question_id/answers/:answer_id/answer_comments/:id/edit' => 'answer_comments#edit', as: :edit_answer_comment

  put 'questions/:question_id/answers/:answer_id/answer_comments/:id' => 'answer_comments#update', as: :update_answer_comment

  post 'questions/:question_id/question_comments/create' => 'question_comments#create', as: :question_comment_create

  get 'questions/:question_id/question_comments/:id/edit' => 'question_comments#edit', as: :edit_question_comment

  put 'questions/:question_id/question_comments/:id' => 'question_comments#update', as: :update_question_comment

  delete 'questions/:question_id/comments/:id' => 'comments#destroy'

  get 'users/login' => 'users#login', as: :login

  post 'users/signin' => 'users#signin'

  get 'users/signout' => 'users#signout', as: :signout

  get 'users/new' => 'users#new', as: :new_user

  post 'users/create' => 'users#create', as: :users

  get 'users/:id/edit' => 'users#edit', as: :edit_user

  put 'users/:id' => 'users#update'

  get 'users/:id' => 'users#show', as: :user

  get 'users' => 'users#index', as: :all_users

  delete 'users/:id' => 'users#destroy'

  post "users/:user_id/answers/:answer_id/answer_votes/upvote" => 'answers#upvote', as: :answer_upvote_create

  post "users/:user_id/answers/:answer_id/answer_votes/downvote" => 'answers#downvote', as: :answer_downvote_create

  post "users/:user_id/questions/:question_id/question_votes/upvote" => 'questions#upvote', as: :question_upvote_create

  post "users/:user_id/questions/:question_id/question_votes/downvote" => 'questions#downvote', as: :question_downvote_create

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :body, :user_id, presence: true
  belongs_to :user
  has_many :answers
  has_many :question_comments
  has_many :question_votes
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if session[:user].nil?
      redirect_to root_path
    else
      @user = User.find(session[:user])
      @user.questions << @question
      if @question.save
        redirect_to question_path(@question)  #user/:id/question/:id
        ## if every question is unique, then the path can be questions/:id, this would be a show controller method
      else
        render :new
      end
    end
  end

  def destroy
    @question=Question.find params[:id]
    user = User.find(@question.user_id)
    @question.destroy
    @user
    redirect_to user_path(user)
  end

  def edit
    @question = Question.find(params[:id])
    if session[:user] == @question.user_id
      @question = Question.find(params[:id])
    else
      redirect_to question_path(@question)
    end
  end

  def update
    @question = Question.find(params[:id])
    @question.body = params[:body]
    @user = @question.user_id
    if @question.update(question_params)
      redirect_to user_path(@user)
    else
      redirect_to :edit_question
    end
  end

  def upvote
    @question = Question.find params[:question_id]
    @user = User.find params[:user_id]
    previous_vote = @user.question_votes.where(:question_id => @question.id, user_id: @user.id).first
    if previous_vote == nil
      @question_vote = QuestionVote.create( :upvote => true )
    else
      QuestionVote.find(previous_vote.id).destroy
      @question_vote = QuestionVote.create( :upvote => true, :downvote => false )
    end
    @user.question_votes << @question_vote
    @question.question_votes << @question_vote
    redirect_to question_path(@question)
  end

  def downvote
    @question = Question.find params[:question_id]
    @user = User.find params[:user_id]
    previous_vote = @user.question_votes.where(:question_id => @question.id, user_id: @user.id).first
    if previous_vote == nil
      @question_vote = QuestionVote.create( :downvote => true )
    else
      QuestionVote.find(previous_vote.id).destroy
      @question_vote = QuestionVote.create( :upvote =>  false, :downvote => true )
    end
    @user.question_votes << @question_vote
    @question.question_votes << @question_vote
    redirect_to question_path(@question)
  end


  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/views/questions/edit.html.erb
<div class="question-view span_4_of_4">
  <h1 class="user-greeting span_4_of_4">Edit your question</h1>
    <%= form_for @question do |f| %>
        <h2><%= f.label "QUESTION TEXT" %></h2>
      <div>
        <%= f.text_field :body, :id => 'question-edit-input' %>
      </div>
        <%= f.submit :class => "menu-button"%>
    <% end%>
</div>

app/views/questions/index.html.erb
<div id="questions-list" class="span_4_of_4">
  <h1>TOP QUESTIONS!</h1>
  <ul>
    <% @questions.each do |question| %>
      <li>
      <div class="answer-count">Answers: <%= question.answers.length %></div>
      <div class="vote-count">Votes: <%= question.question_votes.length %></div>
      <div><%= link_to question.title, question_path(question) %> - <%= link_to question.user.username, user_path(question.user) %></div>
      </li>
    <% end %>
  </ul>
</div>

app/views/questions/new.html.erb
<div id="question-form" class="span_4_of_4">
  <h1>CREATE A NEW QUESTION!</h1>
  <ul>
    <%= form_for @question do |f| %>
    <li>
      <%= f.label :title %>
      <%= f.text_field :title, :id => 'question-title-input' %>
    </li>
    <li>
      <%= f.label :body%>
      <%= f.text_field :body, :id => 'question-body-input' %>
    </li>
    <li>
      <%= f.submit :class => 'menu-button' %>
    </li>
  <% end%>
  </ul>
</div>

app/views/questions/show.html.erb
<% if session[:user] != nil%>
  <% @user = User.find(session[:user]) %>
    <div class="user-greeting span_4_of_4">
      <h1> Hello <%= link_to @user.username, user_path(@user) %> </h1>
    </div>
<% end %>

<div class="single-question-view span_4_of_4">
  <h2 class="question-title"><%= @question.title %></h2>
  <h3 class="question-body"><%= @question.body %>
    <div>
      <button class="upvote-button"><%= link_to "upvote", question_upvote_create_path(@user.id,@question.id), method: :post%></button>
      <button class="downvote-button"><%= link_to "downvote", question_downvote_create_path(@user.id,@question.id), method: :post%></button>
      total votes: <%= @question.question_votes.where(question_id: @question.id,:upvote => true).length %></h3>
   </div>
  <div class="edit-delete">
     <% if session[:user] == @question.user.id %>
       <button class="menu-button"><%= link_to 'edit your question', edit_question_path(@question) %></button>
       <button class="menu-button"><%= link_to 'delete your question', question_path(@question), :method => :delete %></button>
     <% end %>
  </div>
</div>


  <div class="comments span_2_of_4">
  <h3>COMMENTS ON THIS QUESTION:</h3>
    <ol>
      <% @question.question_comments.each do |question_comment| %>
        <li><h2 class="comment"><%= question_comment.body %></h2></li>
        <% if session[:user] == question_comment.user.id %>
          <button class="menu-button">
            <%= link_to "edit your comment", edit_question_comment_path(@question, question_comment) %>
          </button>
        <% end%>
      <% end %>
      <% if session[:user] != nil %>
        <%= render template: "question_comments/new", locals: { question_comment:   QuestionComment.new, question: @question}  %>
      <% end %>
   </ol>
  </div>

 <div class="answers span_2_of_4">
 <h3>ANSWERS TO THIS QUESTION:</h3>
 <ol>
    <% @question.answers.each do |answer| %>
  <li>
      <h2 class="answer"><%= answer.body %> - <%= link_to answer.user.username, user_path(answer.user) %></h2>
        <button class="upvote-button">
          <%= link_to "upvote", answer_upvote_create_path(@user.id,answer.id), method: :post%>
        </button>
        <button class="downvote-button">
          <%= link_to "downvote", answer_downvote_create_path(@user.id,answer.id), method: :post%>
        </button>
           total votes: <%= answer.answer_votes.where(answer_id: answer, upvote: true).length%>
  </li>
  <button id="answer-comments-view"class="menu-button">COMMENTS</button>
   <span class="edit-delete">
      <% if session[:user] == answer.user.id %>
        <button class="menu-button"><%= link_to 'edit', edit_answer_path(@question, answer) %></button>
        <button class="menu-button"><%= link_to 'delete', delete_answer_path(@question.id, answer.id), :method => :delete %></button>
      <% end%>
    </span>
  <div class="answer-comments">
    <p><% answer.answer_comments.each do |comment|%></p>
    <ul>
      <li>
        <h2 class="comment"><%= comment.body %> - <%= link_to comment.user.username, user_path(comment.user) %></h2>
          <% if session[:user] == comment.user.id %>
            <button class="menu-button">
              <%= link_to "edit your comment", edit_answer_comment_path(@question, answer, comment) %>
            </button>
          <% end %>
          <% end %>
          <% if session[:user] != nil %>
            <%= render template: "answer_comments/new", locals: { answer_comment: AnswerComment.new, answer: answer }%>
          <% end %>
        </div>
      </li>
    </ul>
  </li>
 <% end %>

  <% unless session[:user].nil? %>
    <%= render template: "answers/new", locals: { answer: Answer.new, question_id: @question.id } %>
  <% end %>
</ol>