config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get 'questions/index' => 'questions#index', as: :all_questions

  get 'questions/new' => 'questions#new', as: :new_question

  post 'questions/create' => 'questions#create', as: :questions

  get 'questions/:id' => 'questions#show', as: :question

  delete 'questions/:id' => 'questions#destroy'

  get 'questions/:id/edit' => 'questions#edit', as: :edit_question

  patch 'questions/:id' => 'questions#update'

  post 'questions/:question_id/answers/create' => 'answers#create', as: :answer_create

  get 'questions/:question_id/answers/:id/edit' => 'answers#edit', as: :edit_answer

  put 'questions/:question_id/answers/:id' => 'answers#update', as: :update_answer

  delete 'questions/:question_id/answers/:id' => 'answers#destroy', as: :delete_answer

  post 'questions/:question_id/answers/:answer_id/answer_comments/create' => 'answer_comments#create', as: :answer_comment_create

  get 'questions/:question_id/answers/:answer_id/answer_comments/:id/edit' => 'answer_comments#edit', as: :edit_answer_comment

  put 'questions/:question_id/answers/:answer_id/answer_comments/:id' => 'answer_comments#update', as: :update_answer_comment

  post 'questions/:question_id/question_comments/create' => 'question_comments#create', as: :question_comment_create

  get 'questions/:question_id/question_comments/:id/edit' => 'question_comments#edit', as: :edit_question_comment

  put 'questions/:question_id/question_comments/:id' => 'question_comments#update', as: :update_question_comment

  delete 'questions/:question_id/comments/:id' => 'comments#destroy'

  get 'users/login' => 'users#login', as: :login

  post 'users/signin' => 'users#signin'

  get 'users/signout' => 'users#signout', as: :signout

  get 'users/new' => 'users#new', as: :new_user

  post 'users/create' => 'users#create', as: :users

  get 'users/:id/edit' => 'users#edit', as: :edit_user

  put 'users/:id' => 'users#update'

  get 'users/:id' => 'users#show', as: :user

  get 'users' => 'users#index', as: :all_users

  delete 'users/:id' => 'users#destroy'

  post "users/:user_id/answers/:answer_id/answer_votes/upvote" => 'answers#upvote', as: :answer_upvote_create

  post "users/:user_id/answers/:answer_id/answer_votes/downvote" => 'answers#downvote', as: :answer_downvote_create

  post "users/:user_id/questions/:question_id/question_votes/upvote" => 'questions#upvote', as: :question_upvote_create

  post "users/:user_id/questions/:question_id/question_votes/downvote" => 'questions#downvote', as: :question_downvote_create

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :first_name, :last_name, :email, :username, presence: true
  validates :password_hash, length: { in: 6..60 }
  has_many :questions
  has_many :answers
  has_many :question_comments
  has_many :answer_comments
  has_many :question_votes
  has_many :answer_votes


end

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController

  def login
    @user = User.new
  end

  def index
    @users = User.all
  end

  def signin
    @user = User.find_by_username(params[:username])
    if @user && BCrypt::Password.new(@user.password_hash) == params[:password]
      session[:user] = @user.id
      redirect_to user_path(@user)
    else
      render :login
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    hash = BCrypt::Password.create(params[:user][:password])
    @user.password_hash = hash

    if @user.save
      session[:user] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end

  end

  def edit
    @user=User.find(params[:id])
    if session[:user] == @user.id
      @user=User.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    @user=User.find params[:id]
    hash = BCrypt::Password.create(params[:password])
    if @user.update_attribute :password_hash, hash
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    user=User.find params[:id]
    session[:user] = nil
    user.destroy
  end

  def signout
    session[:user] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password_hash)
  end

end

app/views/users/edit.html.erb
<h1>Edit your password</h1>
<ul>
<%= form_for @user do |f| %>
  <li>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </li>
  <li>
    <%= f.submit %>
  </li>

<% end%>
</ul>

app/views/users/index.html.erb
<div id="users-list">
  <h1 class="user-greeting span_4_of_4">USERS</h1>
  <ul>
    <% @users.each do |user| %>
      <li class="user-name">
      <div><%= user.first_name %> <%= user.last_name %> - <%= link_to user.username, user_path(user) %></div>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/login.html.erb
<h1 class="user-greeting span_4_of_4">LOGIN!</h1>
<div class="user-login">
  <ul>
    <li>
      <%= form_tag :action => :signin do  %>
    </li>
    <li>
      <%= label_tag :username %>
      <%= text_field_tag :username %><br>
    </li>
    <li>
      <%= label_tag :password %>
      <%= password_field_tag :password %><br>
    </li>
    <%= submit_tag :Login, :class=> 'menu-button'%>
    <% end %>
 </ul>
</div>

app/views/users/new.html.erb
<h1 class="user-greeting span_4_of_4">SIGN UP!</h1>
<div class="user-signup">
  <ul>
    <%= form_for @user do |u| %>
    <li>
      <%= u.label :first_name %>
      <%= u.text_field :first_name %><br>
    </li>
    <li>
      <%= u.label :last_name %>
      <%= u.text_field :last_name %><br>
    </li>
    <li>
      <%= u.label :username %>
      <%= u.text_field :username %><br>
    </li>
    <li>
      <%= u.label :email %>
      <%= u.text_field :email %><br>
    </li>
    <li>
      <%= u.label :password %>
      <%= u.password_field :password %><br>
    </li>
  </ul>
    <%= u.submit :Create!, :class=> 'menu-button', :id => 'create-user-button'%>
    <% end %>
</div>

app/views/users/show.html.erb
<div id="user-profile" class="span_4_of_4">
  <% if session[:user] == @user.id %>
      <h1>Welcome <%= @user.username %></h1>
      <button class="menu-button"><%= link_to "edit your profile", edit_user_path(@user) %></button>
  <% end%>
  <% if session[:user] != @user.id %>
    <h1 class="user-greeting span_4_of_4">QUESTIONS FROM <%= @user.username %></h1>
  <% end%>
      <% @user.questions.each do |q|%>
      <h4 class="question-title"><%= link_to q.title, question_path(q) %></h4>
      <p class="question-body"><%= q.body %></p>
    <% end %>
</div>